#!/usr/bin/env bash
# 1-init-install.sh
# STEP 1: Phoenix toolchain + nginx on fresh Rocky Linux 10.
# Self-contained — no config file dependency. Prompts for service user name.
# Generates installation.conf for STEP 2. Downloads 2-configure.sh.
#
# Run AS your sudo login user (not root, not the target service user).
# Idempotent — safe to re-run.

set -euo pipefail

# ---- hardcoded latest versions (May 2026) ----
ASDF_VER="0.19.0"
ERLANG_VER="28.5"
ELIXIR_VER="1.19.5-otp-28"

CONFIGURE_URL="https://raw.githubusercontent.com/maliktuwaidan/maj-scripts/main/rocky-linux/10/phoenix-framework+nginx+service-user/2-configure.sh"

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# ---- preflight ----
[[ $EUID -eq 0 ]] && { echo "ERROR: run as a sudo user, not root."; exit 1; }
sudo -v || { echo "ERROR: sudo required."; exit 1; }

# ---- prompt: service user name ----
echo
read -rp "Service user name (e.g. galasin-svc): " SVC_USER
SVC_USER="${SVC_USER// /}"
[[ -n "$SVC_USER" ]] || { echo "ERROR: service user name required."; exit 1; }
[[ "$SVC_USER" =~ ^[a-z_][a-z0-9_-]{0,31}$ ]] || { echo "ERROR: invalid user name (lowercase letters, digits, -, _; <= 32 chars)."; exit 1; }
[[ "$SVC_USER" != "root" ]] || { echo "ERROR: cannot use root."; exit 1; }
[[ "$SVC_USER" != "$(id -un)" ]] || { echo "ERROR: cannot use your own login user."; exit 1; }

SVC_HOME="/opt/${SVC_USER}"
LOGIN_USER="$(id -un)"

# ---- 1. system packages ----
echo "==> Enabling CRB + EPEL"
sudo dnf install -y dnf-plugins-core
sudo dnf config-manager --set-enabled crb
sudo dnf install -y epel-release

echo "==> Installing build deps, nginx, nodejs"
# Erlang built --without-wx/--without-javac/--without-odbc → no wx/java/odbc deps.
sudo dnf install -y \
    gcc gcc-c++ make automake autoconf \
    ncurses-devel openssl-devel \
    inotify-tools git curl rsync \
    nginx \
    nodejs npm \
    firewalld policycoreutils-python-utils

sudo systemctl enable --now firewalld
sudo systemctl enable nginx

# ---- 2. create service user ----
if id "$SVC_USER" &>/dev/null; then
    echo "==> Service user $SVC_USER already exists"
else
    echo "==> Creating service user $SVC_USER (home: $SVC_HOME)"
    sudo useradd -r -m -d "$SVC_HOME" -s /bin/bash "$SVC_USER"
fi

# ---- 3. install toolchain (as service user) ----
INNER="$(mktemp /tmp/init-inner.XXXXXX.sh)"
chmod 0644 "$INNER"
trap 'rm -f "$INNER"' EXIT

cat > "$INNER" <<'INNER_EOF'
#!/usr/bin/env bash
set -euo pipefail
ASDF_VER="$1"; ERLANG_VER="$2"; ELIXIR_VER="$3"

ASDF_BIN="$HOME/bin/asdf"
export PATH="$HOME/bin:$PATH"
export ASDF_DATA_DIR="$HOME/.asdf"
export PATH="$ASDF_DATA_DIR/shims:$PATH"
export KERL_CONFIGURE_OPTIONS="--without-wx --without-javac --without-odbc"

# asdf binary
if [[ -x "$ASDF_BIN" ]] && "$ASDF_BIN" --version 2>/dev/null | grep -qF "$ASDF_VER"; then
    echo "    asdf v${ASDF_VER} already present"
else
    mkdir -p "$HOME/bin"
    curl -fsSL "https://github.com/asdf-vm/asdf/releases/download/v${ASDF_VER}/asdf-v${ASDF_VER}-linux-amd64.tar.gz" \
        -o /tmp/asdf.tar.gz
    tar -xzf /tmp/asdf.tar.gz -C "$HOME/bin" asdf
    rm -f /tmp/asdf.tar.gz
    chmod +x "$ASDF_BIN"
fi

# shell init
if ! grep -q 'ASDF_DATA_DIR' "$HOME/.bashrc" 2>/dev/null; then
cat >> "$HOME/.bashrc" <<'BASHRC'
# asdf
export PATH="$HOME/bin:$PATH"
export ASDF_DATA_DIR="$HOME/.asdf"
export PATH="$ASDF_DATA_DIR/shims:$PATH"
BASHRC
fi

# plugins
"$ASDF_BIN" plugin add erlang 2>/dev/null || true
"$ASDF_BIN" plugin add elixir 2>/dev/null || true

# Erlang (compiles from source, ~10-20 min)
if "$ASDF_BIN" list erlang 2>/dev/null | grep -qF "$ERLANG_VER"; then
    echo "    Erlang ${ERLANG_VER} already installed"
else
    echo "    Installing Erlang ${ERLANG_VER} (~10-20 min)"
    "$ASDF_BIN" install erlang "$ERLANG_VER"
fi

# Elixir (precompiled, fast)
if "$ASDF_BIN" list elixir 2>/dev/null | grep -qF "$ELIXIR_VER"; then
    echo "    Elixir ${ELIXIR_VER} already installed"
else
    "$ASDF_BIN" install elixir "$ELIXIR_VER"
fi

"$ASDF_BIN" set -u erlang "$ERLANG_VER"
"$ASDF_BIN" set -u elixir "$ELIXIR_VER"
"$ASDF_BIN" reshim

mix local.hex --force
mix local.rebar --force
elixir --version
INNER_EOF

echo "==> Installing toolchain as $SVC_USER"
sudo -u "$SVC_USER" -H bash "$INNER" "$ASDF_VER" "$ERLANG_VER" "$ELIXIR_VER"

# ---- 4. write installation.conf ----
echo "==> Writing ${HERE}/installation.conf"
cat > "${HERE}/installation.conf" <<CONF
# installation.conf
# Generated by 1-init-install.sh on $(date -Iseconds).
# Edit REPLACE_ME values, then run ./2-configure.sh.

# ---- service user (set by 1-init-install.sh — don't change) ----
SVC_USER="${SVC_USER}"
SVC_HOME="${SVC_HOME}"

# ---- toolchain (installed by 1-init-install.sh) ----
ASDF_VER="${ASDF_VER}"
ERLANG_VER="${ERLANG_VER}"
ELIXIR_VER="${ELIXIR_VER}"

# ---- app identity (EDIT — must match your project) ----
APP_NAME="REPLACE_ME_app_name"               # Elixir release name, must match \`app:\` in mix.exs
APP_DOMAIN="REPLACE_ME.example.com"          # public hostname (e.g. behind Cloudflare)
APP_PORT=4000                                # internal bind; nginx proxies here

# ---- paths (REVIEW — derived from APP_NAME and SVC_HOME) ----
SOURCE_DIR="/home/${LOGIN_USER}/REPLACE_ME_app_name"            # where you edit (workflow B)
DEPLOY_DIR="\${SVC_HOME}/REPLACE_ME_app_name"                    # where app builds and runs
ENV_FILE="/etc/REPLACE_ME_app_name/REPLACE_ME_app_name.env"     # secrets, 600, owned by SVC_USER
RELEASE_BIN="\${DEPLOY_DIR}/_build/prod/rel/\${APP_NAME}/bin/\${APP_NAME}"
CONF

# ---- 5. download 2-configure.sh ----
echo "==> Downloading 2-configure.sh"
curl -fsSL "$CONFIGURE_URL" -o "${HERE}/2-configure.sh"
chmod +x "${HERE}/2-configure.sh"

# ---- done ----
cat <<DONE

==> STEP 1 complete.

Installed:
  - System: build deps, nginx, nodejs, firewalld
  - Service user: $SVC_USER (home: $SVC_HOME)
  - asdf $ASDF_VER, Erlang $ERLANG_VER, Elixir $ELIXIR_VER, Hex, rebar

Generated:
  - ${HERE}/installation.conf
  - ${HERE}/2-configure.sh

Next:
  1. EDIT ${HERE}/installation.conf — replace REPLACE_ME values:
       APP_NAME      (e.g. galasin_services)
       APP_DOMAIN    (e.g. service.galasin.com)
       SOURCE_DIR    (where you edit code)
       DEPLOY_DIR    (where it runs — usually \$SVC_HOME/\$APP_NAME)
       ENV_FILE      (/etc/<app_name>/<app_name>.env is conventional)
  2. ./2-configure.sh
DONE
