#!/usr/bin/env bash
# 2-configure.sh
# STEP 2: configure services using installation.conf.
# Generates env file, nginx site, systemd unit, and a standalone deploy.sh.
# Opens firewall ports, sets SELinux, starts nginx.
#
# Run AS your sudo login user.
# Idempotent — safe to re-run (regenerates configs from installation.conf).

set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# ---- load installation.conf ----
[[ -f "${HERE}/installation.conf" ]] || { echo "ERROR: installation.conf missing — run 1-init-install.sh first."; exit 1; }
# shellcheck disable=SC1091
source "${HERE}/installation.conf"

# ---- preflight ----
[[ $EUID -eq 0 ]] && { echo "ERROR: run as a sudo user, not root."; exit 1; }
sudo -v || { echo "ERROR: sudo required."; exit 1; }
id "$SVC_USER" &>/dev/null || { echo "ERROR: $SVC_USER missing — run 1-init-install.sh first."; exit 1; }

if grep -q 'REPLACE_ME' "${HERE}/installation.conf"; then
    echo "ERROR: installation.conf still contains REPLACE_ME placeholders."
    echo "       Edit it first, then re-run."
    grep -n 'REPLACE_ME' "${HERE}/installation.conf"
    exit 1
fi

# ---- 1. env file (empty placeholders, 600, svc-owned) ----
echo "==> Env file: $ENV_FILE"
sudo mkdir -p "$(dirname "$ENV_FILE")"
if [[ -f "$ENV_FILE" ]]; then
    echo "    exists — not overwriting (delete manually if you want a reset)"
else
    sudo install -o "$SVC_USER" -g "$SVC_USER" -m 600 /dev/null "$ENV_FILE"
    sudo tee "$ENV_FILE" >/dev/null <<ENVF
# ${APP_NAME} environment — perms 600, owner ${SVC_USER}.
# Fill values, then: sudo systemctl restart ${APP_NAME}
# systemd EnvironmentFile syntax: KEY=value (no quotes, no export).

# --- web ---
PHX_SERVER=true
PHX_HOST=${APP_DOMAIN}
PORT=${APP_PORT}

# --- secrets ---
# Generate SECRET_KEY_BASE: sudo -iu ${SVC_USER} bash -lc 'cd ${DEPLOY_DIR} && mix phx.gen.secret'
SECRET_KEY_BASE=

# --- database ---
DATABASE_URL=
POOL_SIZE=10

# --- app keys ---
ADMIN_API_KEY=
MAILJET_API_KEY=
MAILJET_SECRET_KEY=
ENVF
    sudo chown "${SVC_USER}:${SVC_USER}" "$ENV_FILE"
    sudo chmod 600 "$ENV_FILE"
fi

# ---- 2. nginx site config ----
NGINX_CONF="/etc/nginx/conf.d/${APP_NAME}.conf"
echo "==> nginx: $NGINX_CONF"
sudo tee "$NGINX_CONF" >/dev/null <<NGINX
# Generated by 2-configure.sh from installation.conf.
# Re-run 2-configure.sh after editing installation.conf to regenerate.

server {
    listen 80;
    server_name ${APP_DOMAIN};

    location / {
        proxy_pass http://127.0.0.1:${APP_PORT};
        proxy_http_version 1.1;
        proxy_set_header Host              \$host;
        proxy_set_header X-Real-IP         \$remote_addr;
        proxy_set_header X-Forwarded-For   \$remote_addr;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header Upgrade           \$http_upgrade;
        proxy_set_header Connection        "upgrade";
        proxy_read_timeout 300s;
    }
}
NGINX
sudo nginx -t

# ---- 3. systemd unit ----
UNIT_PATH="/etc/systemd/system/${APP_NAME}.service"
echo "==> systemd: $UNIT_PATH"
sudo tee "$UNIT_PATH" >/dev/null <<UNIT
# Generated by 2-configure.sh from installation.conf.
[Unit]
Description=${APP_NAME} (Phoenix)
After=network-online.target
Wants=network-online.target

[Service]
Type=exec
User=${SVC_USER}
Group=${SVC_USER}
WorkingDirectory=${DEPLOY_DIR}
EnvironmentFile=${ENV_FILE}
ExecStart=${RELEASE_BIN} start
ExecStop=${RELEASE_BIN} stop
Restart=on-failure
RestartSec=5
KillMode=mixed
TimeoutStopSec=30

# Hardening (BEAM-compatible — JIT needs W^X so no MemoryDenyWriteExecute)
NoNewPrivileges=true
PrivateTmp=true
ProtectSystem=full
ProtectHome=true
ProtectKernelTunables=true
ProtectKernelModules=true
ProtectControlGroups=true
RestrictSUIDSGID=true
LockPersonality=true
RestrictRealtime=true

[Install]
WantedBy=multi-user.target
UNIT

sudo systemctl daemon-reload

# ---- 4. firewall ----
echo "==> Firewall: http, https"
sudo firewall-cmd --permanent --add-service=http
sudo firewall-cmd --permanent --add-service=https
sudo firewall-cmd --reload

# ---- 5. SELinux ----
echo "==> SELinux: httpd_can_network_connect"
sudo setsebool -P httpd_can_network_connect 1

# ---- 6. start nginx, enable app service ----
echo "==> Reloading nginx, enabling ${APP_NAME}.service"
sudo systemctl reload-or-restart nginx
sudo systemctl enable "${APP_NAME}"

# ---- 7. generate standalone deploy.sh (no installation.conf dependency) ----
echo "==> Generating ${HERE}/deploy.sh (self-contained)"
cat > "${HERE}/deploy.sh" <<DEPLOY_EOF
#!/usr/bin/env bash
# deploy.sh — generated by 2-configure.sh on $(date -Iseconds).
# Self-contained: all values baked in below. No installation.conf dependency.
# Run AS your sudo login user.
# Flags:  --no-restart    build only

set -euo pipefail

# === baked-in values ===
APP_NAME="${APP_NAME}"
SVC_USER="${SVC_USER}"
SOURCE_DIR="${SOURCE_DIR}"
DEPLOY_DIR="${DEPLOY_DIR}"
APP_DOMAIN="${APP_DOMAIN}"
APP_PORT="${APP_PORT}"

# === preflight ===
[[ \$EUID -eq 0 ]] && { echo "ERROR: run as a sudo user, not root."; exit 1; }
sudo -v || { echo "ERROR: sudo required."; exit 1; }
[[ -d "\$SOURCE_DIR" ]] || { echo "ERROR: source dir \$SOURCE_DIR missing."; exit 1; }
id "\$SVC_USER" &>/dev/null || { echo "ERROR: \$SVC_USER missing."; exit 1; }

RESTART=1
[[ "\${1:-}" == "--no-restart" ]] && RESTART=0

# === 1. rsync source -> deploy dir ===
echo "==> rsync \$SOURCE_DIR -> \$DEPLOY_DIR"
sudo mkdir -p "\$DEPLOY_DIR"
sudo rsync -a --delete \\
    --exclude '_build' --exclude 'deps' --exclude '.git' \\
    --exclude 'node_modules' --exclude 'priv/static/assets' \\
    --exclude '.claude' --exclude '.elixir_ls' \\
    --chown="\${SVC_USER}:\${SVC_USER}" \\
    "\${SOURCE_DIR}/" "\${DEPLOY_DIR}/"

# === 2. build + release as service user ===
echo "==> Build + release as \$SVC_USER"
sudo -iu "\$SVC_USER" bash -lc "
    set -euo pipefail
    cd '\$DEPLOY_DIR'
    mix deps.get --only prod
    npm --prefix assets ci
    MIX_ENV=prod mix compile
    MIX_ENV=prod mix assets.deploy
    MIX_ENV=prod mix release --overwrite
"

# DB migrations: run manually when schema changes:
#   sudo -iu \$SVC_USER bash -lc '\$DEPLOY_DIR/_build/prod/rel/\$APP_NAME/bin/\$APP_NAME eval "<App>.Release.migrate"'

# === 3. restart services ===
if [[ "\$RESTART" == "1" ]]; then
    echo "==> Restart \${APP_NAME}.service"
    sudo systemctl restart "\$APP_NAME"
    echo "==> Reload nginx (preserves in-flight connections)"
    sudo systemctl reload nginx
    sleep 2
else
    echo "==> --no-restart given, skipping restart"
fi

# === 4. status of everything ===
echo
echo "--- \${APP_NAME}.service ---"
sudo systemctl status "\$APP_NAME" --no-pager | head -10 || true
echo
echo "--- nginx ---"
sudo systemctl status nginx --no-pager | head -10 || true
echo
echo "--- listening ports ---"
sudo ss -ltnp | grep -E ":(80|443|\${APP_PORT})\\b" || echo "(none of 80/443/\${APP_PORT} listening)"

cat <<MSG

==> Deploy done.

Tail logs:  sudo journalctl -u \${APP_NAME} -f
Smoke test: curl -I http://127.0.0.1:\${APP_PORT}
            curl -I http://127.0.0.1 -H 'Host: \${APP_DOMAIN}'
MSG
DEPLOY_EOF
chmod +x "${HERE}/deploy.sh"

# ---- done ----
cat <<DONE

==> STEP 2 complete.

Configured:
  - $ENV_FILE                    (empty placeholders — FILL THESE)
  - $NGINX_CONF
  - $UNIT_PATH                   (enabled, NOT started — needs a release first)
  - Firewall: http, https
  - SELinux: httpd_can_network_connect
  - ${HERE}/deploy.sh             (self-contained, no installation.conf dependency)

Next:
  1. Fill secrets in $ENV_FILE
     Generate SECRET_KEY_BASE:
       sudo -iu $SVC_USER bash -lc 'mix phx.gen.secret'
  2. Install/configure PostgreSQL separately (restore data, align port, fix ownership).
  3. Place source code at $SOURCE_DIR
  4. ./deploy.sh
  5. sudo systemctl start $APP_NAME
DONE
